/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : IBNBeaconFSM.sm
 */


#import "statemap.h"

// Forward declarations.
@class IBNBeaconMap;
@class IBNBeaconMap_Outside;
@class IBNBeaconMap_Inside;
@class IBNBeaconMap_Far;
@class IBNBeaconMap_Near;
@class IBNBeaconMap_Default;
@class IBNBeaconModelState;
@class IBNBeaconFSM;
@class IBNBeaconModel;

@interface IBNBeaconModelState : SMCState
{
}
- (void)Entry:(IBNBeaconFSM*)context;
- (void)Exit:(IBNBeaconFSM*)context;

- (void)far:(IBNBeaconFSM*)context;
- (void)in:(IBNBeaconFSM*)context;
- (void)near:(IBNBeaconFSM*)context;
- (void)out:(IBNBeaconFSM*)context;

- (void)Default:(IBNBeaconFSM*)context;
@end

@interface IBNBeaconMap : NSObject
{
}
+ (IBNBeaconMap_Outside*)Outside;
+ (IBNBeaconMap_Inside*)Inside;
+ (IBNBeaconMap_Far*)Far;
+ (IBNBeaconMap_Near*)Near;
@end

@interface IBNBeaconMap_Default : IBNBeaconModelState
{
}
- (void)Default:(IBNBeaconFSM*)context;
@end

@interface IBNBeaconMap_Outside : IBNBeaconMap_Default
{
}
 -(void)Entry:(IBNBeaconFSM*)context;
- (void)in:(IBNBeaconFSM*)context;
@end

@interface IBNBeaconMap_Inside : IBNBeaconMap_Default
{
}
 -(void)Entry:(IBNBeaconFSM*)context;
- (void)far:(IBNBeaconFSM*)context;
- (void)near:(IBNBeaconFSM*)context;
- (void)out:(IBNBeaconFSM*)context;
@end

@interface IBNBeaconMap_Far : IBNBeaconMap_Default
{
}
 -(void)Entry:(IBNBeaconFSM*)context;
- (void)near:(IBNBeaconFSM*)context;
- (void)out:(IBNBeaconFSM*)context;
@end

@interface IBNBeaconMap_Near : IBNBeaconMap_Default
{
}
 -(void)Entry:(IBNBeaconFSM*)context;
- (void)far:(IBNBeaconFSM*)context;
- (void)out:(IBNBeaconFSM*)context;
@end

@interface IBNBeaconFSM : SMCFSMContext
{
    __weak IBNBeaconModel *_owner;
}
- (id)initWithOwner:(IBNBeaconModel*)owner;
- (id)initWithOwner:(IBNBeaconModel*)owner state:(SMCState*)aState;
- (IBNBeaconModel*)owner;
- (IBNBeaconModelState*)state;

- (void)enterStartState;

- (void)far;
- (void)in;
- (void)near;
- (void)out;
@end


/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
